apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "true"
  name: ingress-tekton-insights
  namespace: hcc-pipeline-tenant
spec:
  application: ingress
  contexts:
  - description: Application testing
    name: application
  params:
  - name: APP_NAME
    value: ingress
  - name: COMPONENT_NAME
    value: ingress
  - name: IQE_PLUGINS
    value: ingress
  - name: IQE_MARKER_EXPRESSION
    value: smoke
  resolverRef:
    params:
    - name: url
      value: https://github.com/gbenhaim/tekton-insights.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
