apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - integration_test_scenario.yaml              #Ingress
  - integration_test_tekton.yaml                #Ingress
  - release_plan.yaml                           #Ingress
  - playbook_dispatcher_integration_test.yaml
  - playbook_dispatcher_tekton_test.yaml
  - playbook_dispatcher_release_plan.yaml 
  - ../../../../lib/consoledot-test-pipeline
namespace: hcc-pipeline-tenant
